### ISSUE TITLE
Check references to old main branch

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/manual#14]
As this branch is deleted here on GitHub as the deploy-book-workflow allows all branches to be seen

**Comment by xjulie0x** [comment]
from now on merge directly to release?

**Comment by Tom-van-Woudenberg** [comment]
Yes

**Comment by Tom-van-Woudenberg** [comment]
With this issue I meant for example the page in hypothesis

**Comment by Tom-van-Woudenberg** [comment]
Done for hypothesis page, so I'll close this for now
