### ISSUE TITLE
Issue on page /external/deploy-book-workflow/README.html

### ISSUE THREAD

**Issue by FreekPols** [TeachBooks/manual#22]
page could use further explanation!

**Comment by Tom-van-Woudenberg** [comment]
What do you miss @freekpols?

**Comment by Tom-van-Woudenberg** [comment]
> What do you miss @freekpols?

@FreekPols

**Comment by FreekPols** [comment]
Ik pak t eind januari op, dan lees ik alle teksten en doe voorstellen voor aanpassing

**Comment by Tom-van-Woudenberg** [comment]
I'll close this for now
