### ISSUE TITLE
Issue on page /workflows/edit_book.html

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/manual#33]
Fix width align options, maybe add --- before and after options?

**Comment by xjulie0x** [comment]
you mean that some figures only have a width or align specification and that it should be consistent throughout the page?

**Comment by Tom-van-Woudenberg** [comment]
No, on the built book the options are visible in the caption

**Comment by xjulie0x** [comment]
ah i see, will fix
