### ISSUE TITLE
Add APA referencing

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/manual#35]
Both as content as references itself

**Comment by Tom-van-Woudenberg** [comment]
@rlanzafame  knows how to do this

**Comment by Tom-van-Woudenberg** [comment]
Also add a description as a feature

**Comment by rlanzafame** [comment]
on in PR 38 https://github.com/TeachBooks/manual/pull/38
plan to make it an extension in Project 17 https://github.com/orgs/TeachBooks/projects/17
